version: "3.5"

services:
  mysql:
    image: mysql:8.0
    container_name: push_study_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
  app:
    build:
      context: .
      target: builder
    volumes:
      - ./:/app
    command: realize start --server
    environment:
      - API_VERSION=development
      - LOCAL_HEROKU_IMG_APP_DATABASE_URL
    ports:
      - 5002:5002
    depends_on:
      - mysql
