version: "3.5"

services:
  app:
    container_name: image-app-hotload
    build:
      context: .
      target: builder
    volumes:
      - ./:/app
    command: realize start --server
    environment:
      - API_VERSION=development
      - LOCAL_HEROKU_IMG_APP_DATABASE_URL
    ports:
      - 5002:5002
        #depends_on:
        #  - mysql
