version: "3.5"

services:
  mysql:
    image: mysql:8.0
    container_name: image-mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306

  app:
    container_name: image-app-hotload
    build:
      context: .
      target: builder
    volumes:
      - ./:/app
    command: reflex -r '\.go$$' -s -- sh -c 'go run cmd/api/main.go'
    environment:
      - API_VERSION=development
      - DATABASE_DATASOURCE
    ports:
      - 5002:5002
      - 8080:8080
    depends_on:
        - mysql
